### ISSUE TITLE
Tests failing on Windows 10 machine 

### ISSUE THREAD

**Issue by zac11** [igniteram/puppeteer-cucumber-typescript#10]
Hi,

Thanks for this set-up. I was looking for this kind of set-up with Puppeteer.
I was trying to run this set up on a Windows 10 machine. But I am getting error whenever I try to run the `npm test` command.

Stack Trace : 

```
C:\Projects\puppeteer-cucumber-typescript>npm test

> puppeteer-cucumber-typescript@0.1.1 pretest C:\Projects\puppeteer-cucumber-typescript
> ts-node ./utils/json.ts


> puppeteer-cucumber-typescript@0.1.1 test C:\Projects\puppeteer-cucumber-typescript
> npm run cucumber && npm run report


> puppeteer-cucumber-typescript@0.1.1 cucumber C:\Projects\puppeteer-cucumber-typescript
> cucumber-js ./features/*.feature --require-module ts-node/register --require './src/*/*.ts' --format 'json:./reports/json/cucumber_report.json'

Error: Cannot find module 'C:\Projects\puppeteer-cucumber-typescript\'json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.require [as loadCustomFormatter] (C:\Projects\puppeteer-cucumber-typescript\node_modules\cucumber\src\formatter\builder.js:73:29)
    at Function.loadCustomFormatter [as getConstructorByType] (C:\Projects\puppeteer-cucumber-typescript\node_modules\cucumber\src\formatter\builder.js:47:33)
    at Function.getConstructorByType [as build] (C:\Projects\puppeteer-cucumber-typescript\node_modules\cucumber\src\formatter\builder.js:17:40)
    at build (C:\Projects\puppeteer-cucumber-typescript\node_modules\cucumber\src\cli\index.js:51:31)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Projects\puppeteer-cucumber-typescript\node_modules\bluebird\js\release\async.js:131:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer-cucumber-typescript@0.1.1 cucumber: `cucumber-js ./features/*.feature --require-module ts-node/register --require './src/*/*.ts' --format 'json:./reports/json/cucumber_report.json'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer-cucumber-typescript@0.1.1 cucumber script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rahul\AppData\Roaming\npm-cache\_logs\2018-09-27T12_04_05_678Z-debug.log
npm ERR! Test failed.  See above for more details.
```

I tried clearing the cache using `npm cache clean --force` and then re-installed the node modules. But it doesn't work any way. 

I am on a Windows 10 enterprise machine, with node `v10.9.0` and `npm` version is `6.4.1`

**Comment by igniteram** [comment]
@zac11 looks like this is a windows issue, cucumber in windows is not accepting string characters in command line . `--require './src/*/*.ts'  --format 'json:./reports/json/cucumber_report.json'` So all you need to do is remove them -

In package.json -

```

"scripts": {
    "cucumber": "cucumber-js ./features/*.feature --require-module ts-node/register --require ./src/*/*.ts --format json:./reports/json/cucumber_report.json",
  }
```

In the above npm command you can see I have removed the string `require` & `format`, this works in windows, give it a try !

Also I have pushed some changes please do a git pull or clone it afresh !

**Comment by igniteram** [comment]
@zac11 Pushed a new npm script `npm run test-windows` which calls the above commands without string characters and added a note in readme as well. It should be working fine now

![windows-cucumber-issue](https://user-images.githubusercontent.com/15998104/46164793-8ec15b00-c2ac-11e8-8788-b1bd2bafe74e.png)

**Comment by igniteram** [comment]
Closing this issue as it seems to be fixed !
